# Homebrew formula for agentstack 0.18.1.
#
# Generated by packaging/homebrew/render-formula.py from the checksums.txt
# published with release v0.18.1. Do not edit by hand; re-render instead.
class Agentstack < Formula
  desc "One portable manifest, every agent CLI — manage MCP servers + skills across AI coding tools"
  homepage "https://github.com/Tarekkharsa/agentstack"
  version "0.18.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-aarch64-apple-darwin.tar.gz"
      sha256 "c81a8d0aae09d5befde6b549335ccb0c1b1f732249766996ce32d13368310fef"
    end
    on_intel do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-x86_64-apple-darwin.tar.gz"
      sha256 "f43db667990701a83bfb9840f30e02b185045c18ff8b5d9e81f0f8961c7f0f46"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ae102e3c12aef56fd201c27ec28ae7057d89c059c03796c6b64eff14ac35f085"
    end
    on_intel do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f338003c004a6a61c03e2d79c7178132917db17d14ff22ac92707f0481072635"
    end
  end

  def install
    # Homebrew strips an archive's single top-level directory while staging.
    bin.install "agentstack"
  end

  test do
    assert_match "agentstack", shell_output("#{bin}/agentstack --help")
  end
end
