# Homebrew formula for agentstack 0.19.0.
#
# Generated by packaging/homebrew/render-formula.py from the checksums.txt
# published with release v0.19.0. Do not edit by hand; re-render instead.
class Agentstack < Formula
  desc "One portable manifest, every agent CLI — manage MCP servers + skills across AI coding tools"
  homepage "https://github.com/Tarekkharsa/agentstack"
  version "0.19.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-aarch64-apple-darwin.tar.gz"
      sha256 "b255b25e536a802fc3180d852832a5d72a0047a993b0a477f2cc24e6e6c5b89b"
    end
    on_intel do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-x86_64-apple-darwin.tar.gz"
      sha256 "7587305f132bbc1df90764181a0d54ba448d32b5b95f68d8071e98c025c067d2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "180880d33e83473ce8199109c6d6854d4c0cc429a6a37d4b24e029c4a9077e17"
    end
    on_intel do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9d69510a9481576f947c7053ee5885f7381c05a48258858ea7dcd0024a52f2f2"
    end
  end

  def install
    # Homebrew strips an archive's single top-level directory while staging.
    bin.install "agentstack"
  end

  test do
    assert_match "agentstack", shell_output("#{bin}/agentstack --help")
  end
end
