# Homebrew formula for agentstack 0.18.0.
#
# Generated by packaging/homebrew/render-formula.py from the checksums.txt
# published with release v0.18.0. Do not edit by hand; re-render instead.
class Agentstack < Formula
  desc "One portable manifest, every agent CLI — manage MCP servers + skills across AI coding tools"
  homepage "https://github.com/Tarekkharsa/agentstack"
  version "0.18.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-aarch64-apple-darwin.tar.gz"
      sha256 "81171160c313a74f88588580c8451768b7965a7e702844ef86423ce72ce491ac"
    end
    on_intel do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-x86_64-apple-darwin.tar.gz"
      sha256 "fd847bdc34c9835aed8da4351df94471aa18c02d86a2cd1219d0a1f482a6d180"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "08b5fbf3af18555a2298560e925e51f3a53a935452fcd67e2a77c3b9fd24d3f1"
    end
    on_intel do
      url "https://github.com/Tarekkharsa/agentstack/releases/download/v#{version}/agentstack-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "407573111e16289768fd518f730d127d3772ead8ee6c4f5fe7670cf883716a93"
    end
  end

  def install
    # Homebrew strips an archive's single top-level directory while staging.
    bin.install "agentstack"
  end

  test do
    assert_match "agentstack", shell_output("#{bin}/agentstack --help")
  end
end
